eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
server:
  port: 9010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - filters:
            - RemoveRequestHeader=Cookie
            # Remove the first path segment from the route so it return /api/v1/** instead of /inventory-service/api/v1/**
            - StripPrefix=1 
          id: inventory-service-dev
          predicates:
            - Path=/inventory-service/api/v1/**
            - Method=GET,POST,PUT,DELETE
          uri: lb://inventory-service
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:9411

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
