eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    instance:
        hostname: discovery-server
server:
    port: 9000
spring:
    application:
        name: discovery-server
    zipkin:
        base-url: http://zipkin:9411

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true